### ISSUE TITLE
Errore nella API EuropeanVAT

### ISSUE THREAD

**Issue by francescobianco** [openapi-it/OpenApi-PHP#1]
Salve, sto provando ad utilizzare la vostra API europeanVAT per integrarla con alcuni CRM aziendali,
purtroppo dopo mille tentativi riscontro sempre lo stesso problema, la API mi risponde con questo messaggio

```json
{
    "success": false,
    "message": "{\"field\":\"code\",\"message\":\"'Codice Cliente' errato\"} false",
    "error": 202,
    "data": null,
    "trace": "WyJpbmRleC5waHBAMzgiLCJjbGFzcy5BdldzLnBocEAyMDkiLCJpbmRleC5waHBAOTYiXQ=="
}
```

la cosa molto strana è che le altre API funzionano benissimo, come ad esempio quella dei CAP molto utile...

Vi prego per favore di darmi supporto per poter utlizzare la vostra API EuropenVAT

Cordiali Saluti
FB

**Comment by SimoneDesantisAltravia** [comment]
Salve, scusi per il ritardo nella risposta. 
Nei giorni in cui ha fatto questa segnalazione stavamo migrando alcuni dei servizi (tra cui quello che ci segnala) su piattaforma aws 
 per via di un grave disservizio del nostro precedente fornitore. Le risulta ancora il problema segnalato?
